### ISSUE TITLE
should this use fullname() api

### ISSUE THREAD

**Issue by danmarsden** [devlionco/moodle-mod_codescore#12]
https://github.com/devlionco/moodle-mod_codescore/blob/master/reports.php#L68

Many sites configure how names are displayed differently - based on language preference etc - the moodle fullname() api takes care of this for you.

not a blocker for approval.

**Comment by ofriDevlion** [comment]
"Hi @danmarsden,

Thank you very much for addressing the issue and bringing it to our attention. We decided to go with your recommendation, and I've added the commit that fixes the problem. The files that required fixing are:

1. `reports.php`

You can find the commit here: https://github.com/devlionco/moodle-mod_codescore/commit/8065a3cf0cc7df9453c0cd185b6701a5582547c3

Sorry for not splitting the commits into separate issues. I'll make sure to do that in the next commit."
