### ISSUE TITLE
integrates with an external api but it's not clear who "owns" the integration endpoint.

### ISSUE THREAD

**Issue by danmarsden** [devlionco/moodle-mod_codescore#13]
This plugin seems to integrate with an external api https://apireprot.learnapp.io/LionAI/index.php

but it's not clear what that endpoint is - who owns it, how users get a key to use it, what data is stored there etc.

These need to be clearer in the plugins db - if a commercial subscription is required to use the plugin that must also be clear.

**Comment by ofriDevlion** [comment]
Hi @danmarsden,

Thank you very much for addressing the issue and bringing it to our attention. I've added the commit that fixes the problem. The files that required fixing are:

`lang/en/codescore.php`

You can find the commit here: https://github.com/devlionco/moodle-mod_codescore/commit/8065a3cf0cc7df9453c0cd185b6701a5582547c3

Sorry for not splitting the commits into separate issues. I'll make sure to do that in the next commit.
