### ISSUE TITLE
invalid privacy api

### ISSUE THREAD

**Issue by danmarsden** [devlionco/moodle-mod_codescore#14]
The privacy api class implemented is incorrect - you have implemented the null provider class, but your plugin stores user data in a number of tables which will need to be included in the privacy api classes.

More information on the privacy class is here:
https://moodledev.io/docs/apis/subsystems/privacy# 

Sites that use continuous integration processes will not be able to use your plugin because Moodle runs unit tests which check to see if all extra plugins include the privacy class.

As you integrate with a 3rd party api you will also need to implement the bit that explains you export data - more info on that is here:
https://moodledev.io/docs/apis/subsystems/privacy#indicating-that-you-export-data-to-an-external-location

Note this is a blocker for plugins db approval as your plugin integrates with an external api.

**Comment by ofriDevlion** [comment]
Hi @danmarsden,

Thank you very much for addressing the issue and bringing it to our attention. I've added the commit that fixes the problem. The files that required fixing are:

`classes/privacy/provider.php`
`lang/en/codescore.php`
`lang/he/codescore.php`

You can find the commit here: https://github.com/devlionco/moodle-mod_codescore/commit/8065a3cf0cc7df9453c0cd185b6701a5582547c3

Sorry for not splitting the commits into separate issues. I'll make sure to do that in the next commit.
