### ISSUE TITLE
All filename should be in frankenstyle

### ISSUE THREAD

**Issue by purnendudash** [devlionco/moodle-mod_codescore#2]
codeEditor.js should be changed

Ref - https://moodledev.io/general/development/policies/codingstyle/frankenstyle

**Comment by ofriDevlion** [comment]
Hi @purnendudash ,
Thank you very much for addressing the issue and bringing it to our attention. I've added the commit that change thefilenames . The files that required fixing are:

`amd/build/codeeditor.min.js`
`amd/build/codeeditor.min.js.map`
`amd/build/lastattempt.min.js`
`amd/build/lastattempt.min.js.map`
`amd/src/codeeditor.js`
`amd/src/lastattempt.js`

You can find the commit here: https://github.com/devlionco/moodle-mod_codescore/commit/8065a3cf0cc7df9453c0cd185b6701a5582547c3

Sorry for not splitting the commits into separate issues. I'll make sure to do that in the next commit.
