### ISSUE TITLE
sesskey was not being checked in all custom actions

### ISSUE THREAD

**Issue by purnendudash** [devlionco/moodle-mod_codescore#3]
It should be checked in all custom actions

https://moodledev.io/general/development/policies/security/crosssite-request-forgery

**Comment by ofriDevlion** [comment]
Hi @purnendudash ,

Thank you very much for addressing the issue and bringing it to our attention.  We deleted the files(delete_attempts.php, grade.php) that required the sesskey and wrote our methods in classes/external instead, you can find the changes in this commit: https://github.com/devlionco/moodle-mod_codescore/commit/8065a3cf0cc7df9453c0cd185b6701a5582547c3

Sorry for not splitting the commits into separate issues. I'll make sure to do that in the next commit.
