### ISSUE TITLE
SQL indentation was not being followed

### ISSUE THREAD

**Issue by purnendudash** [devlionco/moodle-mod_codescore#4]
https://github.com/devlionco/moodle-mod_codescore/blob/7d84137cd17d408517daf34ef2e60beef09e5a62/locallib.php#L31

Ref: https://moodledev.io/general/development/policies/codingstyle/sql

**Comment by ofriDevlion** [comment]
Hi @purnendudash ,

Thank you very much for addressing the issue and bringing it to our attention. I have added the commit that fixes the problem. Additionally, the files that required fixing are:

- `locallib.php`

https://github.com/devlionco/moodle-mod_codescore/commit/8065a3cf0cc7df9453c0cd185b6701a5582547c3

sorry for not spliting the commits to issues, next commit will be seperated
