### ISSUE TITLE
There are silly mistakes like missing "."

### ISSUE THREAD

**Issue by purnendudash** [devlionco/moodle-mod_codescore#5]
Would request you to test all these code before submit. As we found similar typo in issue #1. 

https://github.com/devlionco/moodle-mod_codescore/blob/7d84137cd17d408517daf34ef2e60beef09e5a62/classes/task/check_attempt.php#L39

**Comment by ofriDevlion** [comment]
Hi @purnendudash ,

Thank you very much for addressing the issue and bringing it to our attention. I have added the commit that fixes the problem. Additionally, the files that required fixing are:

- `classes/task/check_attempt.php`

https://github.com/devlionco/moodle-mod_codescore/commit/8065a3cf0cc7df9453c0cd185b6701a5582547c3

sorry for not spliting the commits to issues, next commit will be seperated
