### ISSUE TITLE
Copyrights statement missing

### ISSUE THREAD

**Issue by purnendudash** [devlionco/moodle-mod_codescore#6]
https://github.com/devlionco/moodle-mod_codescore/blob/master/amd/src/codemirrorlib.js

Seems this is an external library. Please make sure this should be GPL compatible. And should have that written on the top of the file.

Kindly check these for references -

https://moodledev.io/general/community/plugincontribution/thirdpartylibraries
https://moodledev.io/general/community/plugincontribution/checklist#copyrights

**Comment by ofriDevlion** [comment]
Hi @purnendudash ,

Thank you very much for addressing the issue and bringing it to our attention. I have added the commit that fixes the problem. Additionally, the files that required fixing are:

1. `amd/src/codemirrorlib.js`
2. `thirdpartylibs.xml`
https://github.com/devlionco/moodle-mod_codescore/commit/8065a3cf0cc7df9453c0cd185b6701a5582547c3

sorry for not spliting the commits to issues, next commit will be seperated
