### ISSUE TITLE
Classname is not in frankstyle

### ISSUE THREAD

**Issue by purnendudash** [devlionco/moodle-mod_codescore#7]
https://github.com/devlionco/moodle-mod_codescore/blob/7d84137cd17d408517daf34ef2e60beef09e5a62/mod_form.php#L36

Kindly check this for reference

https://moodledev.io/general/development/policies/codingstyle/frankenstyle#class-names

**Comment by danmarsden** [comment]
also various functions in locallib.php do not follow the frankenstyle naming conventions.

note this is a blocker for plugins db approval.

**Comment by ofriDevlion** [comment]
Hi @danmarsden,

Thank you very much for addressing the issue and bringing it to our attention. I've added the commit that fixes the filenames. The files that required fixing are:

`attempt.php`
`classes/external/regrade_attempts.php`
`externallib.php`
`locallib.php`
`report.php`
`reports.php`
`tests/basic_test.php`
`view.php`

You can find the commit here: https://github.com/devlionco/moodle-mod_codescore/commit/8065a3cf0cc7df9453c0cd185b6701a5582547c3

Sorry for not splitting the commits into separate issues. I'll make sure to do that in the next commit.
