### ISSUE TITLE
invalid styles.css

### ISSUE THREAD

**Issue by danmarsden** [devlionco/moodle-mod_codescore#8]
in your styles.css you define a number of generic styles that could clash with core moodle code or other locations where simliar names are used. 

Moodle helpfully adds a number of classes to the body tag based on the path that you can use such as:
eg if you are have a file in mod/assign you would see the following class added to the body tag
path-mod-assign
so if you have an item with the class "filething" on the page you would target it like:
```
.path-mod-assign .filething {
   color: red;
}
```

Please make sure your css classes in styles.css are specific enough so they cannot clash with other core code.

**Comment by ofriDevlion** [comment]
Hi @danmarsden,

Thank you very much for addressing the issue and bringing it to our attention. I've added the commit that fixes the problem. The files that required fixing are:

1. `styles.css`

You can find the commit here: https://github.com/devlionco/moodle-mod_codescore/commit/8065a3cf0cc7df9453c0cd185b6701a5582547c3

Sorry for not splitting the commits into separate issues. I'll make sure to do that in the next commit.
