### ISSUE TITLE
missing require_login checks

### ISSUE THREAD

**Issue by danmarsden** [devlionco/moodle-mod_codescore#9]
many of your files check require_capability but forget to add the require_login() before it - please see:
https://moodledev.io/general/development/policies/security#authenticate-the-user

note that classes and library files are the exception to needing a login check.

**Comment by ofriDevlion** [comment]
Hi @danmarsden,

Thank you very much for addressing the issue and bringing it to our attention. I've added the commit that fixes the problem. The files that required fixing are:

1. `attempt.php`
2. `report.php`
3. `reports.php`
4. `startattempt.php`

You can find the commit here: https://github.com/devlionco/moodle-mod_codescore/commit/8065a3cf0cc7df9453c0cd185b6701a5582547c3

Sorry for not splitting the commits into separate issues. I'll make sure to do that in the next commit.
